export const BLOG = {
    ADDING: "BLOG_ADDING",
    ADDING_SUCCESS: "BLOG_ADDING_SUCCESS",
    ADDING_FAILED: "BLOG_ADDING_FAILED",
    REMOVING: "BLOG_REMOVING",
    REMOVING_SUCCESS: "BLOG_REMOVING_SUCCESS",
    REMOVING_FAILED: "BLOG_REMOVING_FAILED",
    FETCHING_BLOGS: "BLOG_FETCHING_BLOGS",
    FETCHING_BLOGS_SUCCESS: "BLOG_FETCHING_BLOGS_SUCCESS",
    FETCHING_BLOGS_FAILED: "BLOG_FETCHING_BLOGS_FAILED",
    FETCHING_BLOG_POST: "BLOG_FETCHING_BLOG_POST",
    FETCHING_BLOG_POST_SUCCESS: "BLOG_FETCHING_BLOG_POST_SUCCESS",
    FETCHING_BLOG_POST_FAILED: "BLOG_FETCHING_BLOG_POST_FAILED"
}

export const POST = {
    ADDING: "POST_ADDING",
    ADDING_SUCCESS: "POST_ADDING_SUCCESS",
    ADDING_FAILED: "POST_ADDING_FAILED",
    EDITING: "POST_EDITING",
    EDITING_SUCCESS: "POST_EDITING_SUCCESS",
    EDITING_FAILED: "POST_EDITING_FAILED",
    REMOVING: "POST_REMOVING",
    REMOVING_SUCCESS: "POST_REMOVING_SUCCESS",
    REMOVING_FAILED: "POST_REMOVING_FAILED",
    FETCHING_POST: "POST_FETCHING_POST",
    FETCHING_POST_SUCCESS: "POST_FETCHING_POST_SUCCESS",
    FETCHING_POST_FAILED: "POST_FETCHING_POST_FAILED"
}